Adds humans.txt
saglacio/saglac.io-original pull request #121
Opened 2017-10-20 19:12 UTC by GabLeRoux

* Should check one point from #120 checklist
* I did not test the meta file link
* `humans.txt` is a draft here, I removed the 'last updated at'. pain to
  maintain for not much

2017-10-20 19:15 UTC, GabLeRoux commented
Oh well, je ne sais pas si `humans.txt` est sensé rempacer `author` meta tag. TBD

2017-10-20 19:32 UTC, emileber commented
Nah, ça me va que ça remplace le author.

Par contre, je crois que ce fichier peut-être généré avec Jekyll et avoir la `last updated at` date.

2017-10-20 19:34 UTC, emileber requested changes
On pourrait générer le fichiers avec le nouveau `authors.yml`

2017-10-20 19:34 UTC, emileber commented on _layouts/default.html
> +    <link type="text/plain" rel="author" href="{{site.url}}/humans.txt" />
Utilise `{{ '/humans.txt' | relative_url }}` pour que ça marche tout le temps avec github pages.

2017-10-20 19:34 UTC, emileber commented on humans.txt
> +  Lead Organizer and communications: Emile Bergeron
C'est un peu l'inverse des informations dans la FAQ où j'indique que personne n'est officiellement derrière le IO.

2017-10-20 19:37 UTC, GabLeRoux commented on humans.txt
> +  Lead Organizer and communications: Emile Bergeron
Je voulais vérifier si tu faisais les reviews correctement :trollface: 
En fait, j'enlèverais Lead Organizer, mais avoir quelqu'un responsable des communications c'est pas tannat ;)

2017-10-20 19:37 UTC, emileber commented on humans.txt
> +  Lead Organizer and communications: Emile Bergeron
Ça se passe via `info@saglac.io`.

2017-10-20 19:38 UTC, GabLeRoux commented on humans.txt
> +  Lead Organizer and communications: Emile Bergeron
Et qui reçoit ces courriels? un humain? ;)

2017-10-20 19:39 UTC, emileber commented on humans.txt
> +  Lead Organizer and communications: Emile Bergeron
📨  Plusieurs humains 👥  en fait

2017-11-01 00:30 UTC, emileber approved these changes

2017-11-01 00:31 UTC, merged