Add thank you page
saglacio/saglac.io-original pull request #123
Opened 2017-10-21 23:55 UTC by jipiboily

Fixes https://github.com/saglacio/saglac.io/issues/117

2017-10-23 02:03 UTC, emileber requested changes

2017-10-23 02:03 UTC, emileber commented on _includes/footer.html
> +                        <input type="hidden" name="_next" value="//saglac.io/merci" />
Idéalement, tous les liens du saglac devrait être généré par Jekyll, par exemple ici: `{{ '/merci' | relative_url }}`

2017-10-23 02:03 UTC, emileber commented on pages/merci.html
> +                    <h2>Merci</h2>
Le titre pourrait inclure le début de la phrase

> Merci de nous avoir contacté

Ça fait répétitif sinon.

2017-10-23 02:03 UTC, emileber commented on pages/merci.html
> +                <p>Merci de nous avoir contacter. Nous vons répondrons sous peu!</p>
J'aimerais ça qu'on rajoute un bouton de retour à l'accueil ici.

2017-10-23 16:00 UTC, emileber commented
Aussi, il faut faire les PR vers `develop`, à moins que ça soit un hotfix.

2017-10-28 01:46 UTC, jipiboily commented
Vous êtes allés overkill pour un site static avec git flow mais c'est bon, c'est changé! :)

2017-10-28 01:47 UTC, jipiboily commented on pages/merci.html
> +                <p>Merci de nous avoir contacter. Nous vons répondrons sous peu!</p>
Bof, y'a la navigation en haut.

2017-10-28 01:47 UTC, emileber commented
ça fait bien quand on développe une nouvelle page, ou une nouvelle feature, pas un gros overhead, juste un delayed release.

2017-10-28 01:49 UTC, emileber commented on pages/merci.html
> +                <p>Merci de nous avoir contacter. Nous vons répondrons sous peu!</p>
c'est surtout une question de standard, les gens cherchent une action et il n'y a rien, ça brise le flow un peu.

2017-11-01 00:47 UTC, emileber approved these changes

2017-11-01 02:28 UTC, merged