Update favicon
saglacio/saglac.io-original pull request #125
Opened 2017-10-22 02:08 UTC by jipiboily

As downloaded on
https://github.com/saglacio/saglac.io/issues/77#issuecomment-276826933

Fixes https://github.com/saglacio/saglac.io/issues/119

2017-10-22 03:25 UTC, GabLeRoux approved these changes
See ms icon comment, otherwise, everything else looks good to me :+1:

2017-10-22 03:25 UTC, GabLeRoux commented on assets/favicon/browserconfig.xml
> +<browserconfig><msapplication><tile><square70x70logo src="/ms-icon-70x70.png"/><square150x150logo src="/ms-icon-150x150.png"/><square310x310logo src="/ms-icon-310x310.png"/><TileColor>#ffffff</TileCo
Ishthis `src` valid for current file? Seems to grab from root, but file is in a folder. Shouldn’t it be `./` instead?

2017-10-23 02:50 UTC, emileber requested changes
Pour les icons plus petit, je ne garderais que le **IO**, sans le _SAGLAC_.

2017-10-23 02:50 UTC, emileber commented on _layouts/default.html
> +    <link rel="apple-touch-icon" sizes="57x57" href="/assets/favicon/apple-icon-57x57.png">
Tous les URL devraient être du type `{{ '/assets/favicon/apple-icon-57x57.png' | relative_url }}`

2017-10-23 02:50 UTC, emileber commented on assets/favicon/browserconfig.xml
> +<browserconfig><msapplication><tile><square70x70logo src="/ms-icon-70x70.png"/><square150x150logo src="/ms-icon-150x150.png"/><square310x310logo src="/ms-icon-310x310.png"/><TileColor>#ffffff</TileCo
Effectivement, il faudrait voir si on peut les générer avec Jekyll et utiliser encore ici le `relative_url` en plus de mettre le bon path.

2017-10-23 02:50 UTC, emileber commented on assets/favicon/manifest.json
> +   "src": "\/android-icon-36x36.png",
Même chose pour ces paths, il faudrait voir si Jekyll peut les gérer.

2017-10-23 16:00 UTC, emileber commented
Même chose ici, cette PR devrait aller vers `develop`.

2017-10-25 13:40 UTC, paaudet commented
J'ai fait un petit test avec la version la plus petite (16x16) pour essayer d'avoir le meilleur résultat.
Mais je ne peux pas uploader le .ico dans mon message. :/ J'en ai encore beaucoup à apprendre...


![favicon](https://user-images.githubusercontent.com/33093055/32001612-4776d660-b968-11e7-885e-76960b364b38.png)

2017-10-25 13:41 UTC, emileber commented
On dirait "IC" si le O est coupé

2017-10-25 13:49 UTC, paaudet commented
En effet, je voulais voir si on allait quand même sentir le O, malgré l'ablation.
Forcé d'admettre que non ... :P 

Sinon, en le rentrant au complet, ça donne ça : 
![favicon2](https://user-images.githubusercontent.com/33093055/32002133-b32557e6-b969-11e7-860a-07a8c1e0c4d4.png)

2017-10-26 13:51 UTC, paaudet commented
Étant donné que je ne suis encore très nouveau à Github, j'ai préparé un .zip avec 3 fichiers : 152x152 IO+SagLac sur fond noir, 152x152 IO-SagLac sur fond noir et le 16x16.ico. 

J'ai vu dans un autre poste de JP qu'il avait un outil pour préparer les fichiers avec les bons formats et noms. Mais comme ça aussi c'est de l'inconnu, je ne voudrais pas faire "n'importe quoi".

N'hésitez pas à m'avertir si je suis dans le champ ou si je peux vous aider pour autre chose.

[IO_favicon.zip](https://github.com/saglacio/saglac.io/files/1418587/IO_favicon.zip)

2017-10-26 14:13 UTC, emileber commented
@paaudet Le best, c'est d'utiliser https://realfavicongenerator.net/ où tout ce que tu as à faire, c'est uploader l'image que tu veux utiliser.

Mais considérant que c'est déjà fait, je crois qu'on va être capable de prendre juste tes images pour remplacer celles que j'aimais moins dans ce PR.

2017-11-02 01:46 UTC, jipiboily commented
@paaudet pourrais-tu me faire juste le blanc en format plus gros?

Voici les specs:

> Submit a picture (PNG, JPG, SVG...), at least 70x70. 
> Your picture should be 260x260	or more for optimal results.

Merci! :)

2017-11-02 13:16 UTC, paaudet commented
@jipiboily Évidemment!

Tu veux blanc "IO saglac" ou juste "IO".
PNG, Transparent?

2017-11-02 14:23 UTC, jipiboily commented
Juste io. PNG transparent devrait le faire je crois. Tu peux
m'ajouter la source aussi SVP? PSD, AI ou whatever else :)

Merci!

JP Boily

Founder @ Metrics Watch 
( https://metricswatch.com/?utm_source=email&utm_medium=gmail-signature )
 (and a new SaaS, see below) - Email Reports & Real-time Alerts
for Google Analytics

On November 2, 2017 at 9:16 AM, paaudet
(notifications@github.com) wrote:

@jipiboily ( https://github.com/jipiboily ) Évidemment!

Tu veux blanc "IO saglac" ou juste "IO".
PNG, Transparent?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
( https://github.com/saglacio/saglac.io/pull/125#issuecomment-341417296 )
, or mute the thread 
( https://github.com/notifications/unsubscribe-auth/AAOOIZt3C6B5Yr0tnJqqVowJlDUsujXtks5sycCagaJpZM4QByLc )
.

2017-11-02 14:37 UTC, paaudet commented
There you go!

[favicon_logoIO_260.psd.zip](https://github.com/saglacio/saglac.io/files/1438154/favicon_logoIO_260.psd.zip)

2023-05-25 15:26 UTC, jipiboily commented
Closing, as this is from 5+ years ago and there's a new site coming. Thanks everyone! :)

2023-05-25 15:26 UTC, closed without merging