Footer form
saglacio/saglac.io-original pull request #131
Opened 2017-10-25 10:05 UTC by chefjuanpi

fix textarea alignment in mobil

2017-10-25 12:06 UTC, GabLeRoux commented
👍 Ça me semble bon, mais comme j'ai demandé quelques changements dans #130, j'ai recréé une PR avec seulement le changement de classe dans le footer. Voir #132

2017-10-25 14:38 UTC, chefjuanpi commented
sans le changement dans main.scss il marche pas

2017-10-25 14:44 UTC, GabLeRoux commented
Oh alors on reopen, mais effectue les changements du css dans `_custom.scss`, mais dans cette PR 👍

2017-10-25 14:47 UTC, GabLeRoux requested changes
Oh alors on reopen, mais effectue les changements du css dans _custom.scss, mais dans cette PR 👍 Merge develop dans ta branche car #132 est déjà merged ;) Il ne manque que la partie css

2017-10-25 15:23 UTC, GabLeRoux submitted a review, later dismissed
J'ai merged `develop` dans ta pull-request et il y a encore des changements dans `main.scss` ;)

```diff
diff --git a/_sass/_custom.scss b/_sass/_custom.scss
index 47139ed..5cd3f93 100644
--- a/_sass/_custom.scss
+++ b/_sass/_custom.scss
@@ -16,6 +16,7 @@
 }
 
 // fix header overlay getting on top only on mobile
+// Apply the same parametres to textarea on mobile from the other imput elements
 @include breakpoint(mobile) {
     #header-wrapper {
         z-index: -2;
@@ -23,6 +24,14 @@
             z-index: -1;
         }
     }
+    textarea {
+        display: block;
+        width: 100%;
+        font-size: 1em;
+        padding: 1em 0 1em 0;
+        max-width: 30em;
+        margin: 0 auto;
+    }
 }
 
 // fix logo and title display with nav
diff --git a/assets/css/main.scss b/assets/css/main.scss
index b15808e..c5ef548 100644
--- a/assets/css/main.scss
+++ b/assets/css/main.scss
@@ -341,6 +341,7 @@
 			background: none;
 			color: #606167;
 			box-shadow: inset 0px 0px 2px 0px #a0a1a7;
+            width:100%;
 
 			&:hover {
 				box-shadow: inset 0px 0px 2px 0px #606167;
@@ -753,8 +754,8 @@
 			input[type="reset"],
 			button,
 			.button {
-				padding: 0 2.25em 0 2.25em;
-				font-size: 0.9em;
+				padding: 0 1em 0 1em;
+				font-size: 0.8em;
 				min-width: 12em;
 				height: 4em;
 				line-height: 4em;
```

Solution:

```bash
git fetch --all --tags
git checkout develop
git pull
git checkout footer-form
git merge develop
git checkout develop assets/css/main.scss
```

Ensuite vérifie que le résultat est bon

```bash
git push
```

Et ça va être prêt à merger (ps; si tu peux ajouter un screenshot au passage, on va être full content) 🎉

2017-10-25 15:40 UTC, chefjuanpi commented
ohh je n'avait pas rendu compte que chaque push apparaitre ici déjà...

J'ai retourné main.scss comme été avant et j'ai mis mes custom sur _custom.scss

2017-10-26 01:47 UTC, emileber commented
Il y a encore trop de stock dans ce PR, il ne devrait y avoir que les changements apportés, et que les commits reliés.

2017-10-26 11:36 UTC, GabLeRoux commented
Il faut seulement merger develop dans la branche précisément comme j’ai indiqué (je l’ai essayé de mon côté)

2017-10-27 13:05 UTC, chefjuanpi commented
I made all the steps

2017-10-27 14:22 UTC, emileber commented
Non ça ne marche pas encore, il y a encore des changements en double.

Cherry-pick tes changements et fait un `push --force` sur ta branche. 

Il y a trop de commits mélangé qui inclut du stock déjà mergé dans develop et master.

2017-11-06 19:29 UTC, emileber commented
@GabLeRoux Voilà c'est à jour, on pourrait merger, faut juste l'essayer avant pour confirmer.

2017-11-06 20:00 UTC, GabLeRoux commented
> marge wit develop

Marge approuves 👍 
![image](https://user-images.githubusercontent.com/1264761/32461216-2311ec20-c303-11e7-92e6-13992b5a3148.png)

Je test ça ce soir.

2017-11-06 20:03 UTC, emileber commented
haha, ouais j'ai vu, petite typo dans le commit message! 😂

2017-11-07 04:55 UTC, emileber approved these changes
Je l'ai essayé et ça fonctionne!

2017-11-07 04:56 UTC, merged

2017-11-07 13:11 UTC, GabLeRoux commented
Ah merci, je n'ai pas ouvert mon ordinateur hier, j'allais le faire ce matin 👍
Merci à vous deux!