Feature/improve information
saglacio/saglac.io-original pull request #139
Opened 2017-11-01 04:57 UTC by emileber

Related to issue #128 

Grosse PR avec beaucoup de changements.

- Page facebook (invisible en local, à voir si c'est possible facilement de tester, sinon ça va aller en prod pareil)
- Refactor des configs
- Déplacement de fichiers
- Fix css
- Refactor de l'intro
- Déplacement dans la FAQ

![image](https://user-images.githubusercontent.com/3286135/32260627-7595cb00-be9f-11e7-9f9d-2df0b7d40450.png)

2017-11-01 04:58 UTC, emileber commented
Règle aussi #114

2017-11-01 15:28 UTC, GabLeRoux requested changes

2017-11-01 15:28 UTC, GabLeRoux commented on _includes/head.html
> +    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> {% include google-analytics.html %}
Enlève le duplicated `{% include google-analytics.html %}`.

2017-11-01 15:41 UTC, emileber commented on _includes/head.html
> +    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> {% include google-analytics.html %}
Ha, nice catch, l'auto-format fait ça avec les tags Liquid.

2017-11-02 04:16 UTC, emileber commented
@GabLeRoux c'est réglé.

2017-11-02 12:54 UTC, GabLeRoux approved these changes

2017-11-02 16:37 UTC, emileber commented
Pablo a trouvé un petit changement CSS qui m'ait passé sous le nez: https://github.com/saglacio/saglac.io/pull/137#issuecomment-341449290

2017-11-07 05:09 UTC, emileber commented
Screenshot final

![image](https://user-images.githubusercontent.com/3286135/32477981-f464bcfc-c34f-11e7-99a4-6aad9aa82bb1.png)

2017-11-07 05:10 UTC, merged