add talk types, stats and clean parts of the YML file
saglacio/saglac.io-original pull request #163
Opened 2018-10-23 15:53 UTC by jipiboily

I added a shitty script to make some "cool" stats about our events. In the process, I had to add some things and clean some others in the YML file.

2018-10-23 15:55 UTC, jipiboily commented
Example output:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Locations:
Exode Café, Alma
14
Café Bistro du Centre, Arvida
13
Aquarium de l'UQAC
4
La Tour à Bière, à Chicoutimi, dans la salle en haut. Nourriture et alcool disponible.
4
Bar la Zone, à Jonquière, sur la Saint-Dominique (salle à part, sans musique). Nourriture et alcool disponible.
4
Entrecôte Riverin (JONQUIÈRE!!!)
2
mikes_chicoutimi_racine
1
La Cage - Brasserie sportive (Chicoutimi)
1
Baruqac, 555 Boulevard de l'Université, Chicoutimi, QC G7H 2B1. Nourriture, bière et autres breuvages disponibles.
1
HopEra, 2377 Rue Saint Dominique, Jonquière, QC G7X 6L4. Microbrasserie et nourriture!
1
Resto-Bar Le Stade (Chicoutimi)
1
Microbrasse du Lac-St-Jean
1
moulin_a_cie
1
pacini_alma
1

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Talk types:
prog
70
autre
21
sysadmin
18
hardware
7
NO TYPE
1

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Speakers ayant le plus de talks:
Jean-Philippe Boily
{:types=>{"autre"=>2, "prog"=>10}, :total_talks=>12}
Gabriel Le Breton
{:types=>{"prog"=>9, "sysadmin"=>2, "autre"=>1}, :total_talks=>12}
Frederic Trottier-Hebert
{:types=>{"autre"=>1, "prog"=>9, "sysadmin"=>2}, :total_talks=>12}
Steeve Juair
{:types=>{"hardware"=>3, "sysadmin"=>4, "NO TYPE"=>1}, :total_talks=>8}
Émile Bergeron
{:types=>{"prog"=>6, "autre"=>1}, :total_talks=>7}
Kim Desrosiers
{:types=>{"prog"=>1, "sysadmin"=>1, "autre"=>3}, :total_talks=>5}
Joel Trottier-Hebert
{:types=>{"prog"=>4, "sysadmin"=>1}, :total_talks=>5}
Jules Robichaud-Gagnon
{:types=>{"prog"=>4}, :total_talks=>4}
Jessica Lapointe
{:types=>{"prog"=>2, "autre"=>2}, :total_talks=>4}
Julien-Samuel Lacroix
{:types=>{"sysadmin"=>2, "prog"=>1}, :total_talks=>3}

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Nombre de metas:
2
```

2018-10-23 16:28 UTC, emileber requested changes

2018-10-23 16:28 UTC, emileber commented on _data/io-events.yml
> +  location: "Aquarium de l'UQAC"
Les locations sont listées dans un fichier et référencées par clé. Il faut ajuster le reste du fichier, et pas toucher au début qui est dans le bon format.

2018-10-23 16:28 UTC, emileber commented on _data/io-events.yml
> +      authors: Jean-Philippe Gravel
Même chose pour les authors, qui est une liste de clé vers la config des auteurs.

2018-10-23 17:30 UTC, jipiboily commented on _data/io-events.yml
> +  location: "Aquarium de l'UQAC"
Ah shnoutte :/

D'la marde, j'ai déjà largement dépassé le temps logique que je pouvais passer sur ça ces temps-ci :)

Laissons la PR là en attendant ("de la terminer" OR "de la fermer après X mois ou années").

2018-10-23 17:30 UTC, jipiboily commented on _data/io-events.yml
> +  location: "Aquarium de l'UQAC"
Ceci dit, c'est ben logique! :)

2018-10-23 17:43 UTC, emileber commented on _data/io-events.yml
> +  location: "Aquarium de l'UQAC"
Ouais, anyway, on a déjà les stats, c'était l'objectif pour ce soir!

2018-10-23 17:46 UTC, jipiboily commented on _data/io-events.yml
> +  location: "Aquarium de l'UQAC"
Exactement!

2023-05-25 15:28 UTC, jipiboily commented
Irrelevant with the new site coming.

2023-05-25 15:28 UTC, closed without merging