Feature/new website template
saglacio/saglac.io-original pull request #82
Opened 2017-10-16 05:49 UTC by emileber

Voici la version 2.0 alpha avec seulement la landing page.

![image](https://user-images.githubusercontent.com/3286135/31597027-20aabce6-b214-11e7-918d-978c961b5f5a.png)

2017-10-16 10:01 UTC, jipiboily commented
Good job!!! So much better 😁

2017-10-16 10:06 UTC, jipiboily reviewed
Looks good! Not sure it's fully done...? It looks like a few things are missing at first and there's a few nitpicks too.

Hope that helps!

2017-10-16 10:06 UTC, jipiboily commented on .travis.yml
> +- 2.2.2
this is an old version, but meh...we don't really care :)

2017-10-16 10:06 UTC, jipiboily commented on _data/authors.yml
> +emileber:
I guess we will need to add everyone who ever did a talk in that file?

2017-10-16 10:06 UTC, jipiboily commented on _includes/footer.html
> +</footer> -->
remove `-->`?

2017-10-16 10:06 UTC, jipiboily commented on _includes/next-io.html
> +        <!-- <a href="#" class="image featured">
remove commented code?

2017-10-16 10:06 UTC, jipiboily commented on _includes/next-io.html
> +                <!-- <li><a href="#" class="button style2 big">More Info</a></li> -->
remove commented code?

2017-10-16 10:06 UTC, jipiboily commented on _includes/testimonials.html
> +<div class="wrapper style3">
This is dummy text FYI.

2017-10-16 10:06 UTC, jipiboily commented on _includes/top_nav.html
> +        <!-- <li><a href="/openhack">OpenHack</a></li> -->
remove instead of comment IMHO.

2017-10-16 10:06 UTC, jipiboily commented on _includes/top_nav.html
> +<!-- <div id='top-nav'>
remove instead of comment IMHO.

2017-10-16 10:06 UTC, jipiboily commented on index.html
> +                    <!-- <h1>Saglac IO</h1> -->
why is this commented?

2017-10-16 10:06 UTC, jipiboily commented on index.html
> +<!-- <div id='event-panels'>
remove instead of comment IMHO

2017-10-16 14:43 UTC, emileber commented on _includes/footer.html
> +</footer> -->
Faudrait que je cleanup, j'ai laissé une couple d'affaire du vieux site comme référence durant que je remplaçais dans le nouveau.

2017-10-16 14:44 UTC, emileber commented on _includes/next-io.html
> +        <!-- <a href="#" class="image featured">
Nah, lui il va finir par servir, j'ai juste pas eu le temps d'intégrer l'image des event facebook ou l'image de l'event tout court.

2017-10-16 14:45 UTC, emileber commented on _includes/next-io.html
> +                <!-- <li><a href="#" class="button style2 big">More Info</a></li> -->
J'aimerais ça qu'il serve aussi, mais je ne lui ai pas encore trouvé de fonctionnalité 😐

2017-10-16 14:46 UTC, emileber commented on _includes/testimonials.html
> +<div class="wrapper style3">
Cette section n'est pas encore intégré, mais elle va contenir les témoignages, ou les derniers événements (mais c'est moins pertinents).

2017-10-16 14:46 UTC, emileber commented on _includes/top_nav.html
> +        <!-- <li><a href="/openhack">OpenHack</a></li> -->
Ça va probablement revenir, donc j'ai seulement commenté ce que je ne veux pas qui apparaisse pour l'instant.

2017-10-16 14:47 UTC, emileber commented on _includes/top_nav.html
> +<!-- <div id='top-nav'>
Ça faut effectivement l'enlever.

2017-10-16 14:48 UTC, emileber commented on index.html
> +                    <!-- <h1>Saglac IO</h1> -->
Parce que c'est le logo qui est affiché, pas le titre en texte. Il y a surement un moyen facile d'afficher les 2 pour le référencement, mais pour l'instant, j'y vais pour la fonctionnalité, après, on fera une PR référencement au besoin.

2017-10-16 14:50 UTC, emileber commented
Gardez en tête que c'est l'alpha, j'ai seulement mis la landing page et j'ai commenté beaucoup de section dans le but d'avoir de quoi de fonctionnel pour demain.

2017-10-16 14:51 UTC, emileber commented
J'ai aussi retravaillé la structure des datas pour avoir une plus grande souplesse et moins de répétition lors d'ajout d'événement.

Il faudra éventuellement migrer les vieilles données.

2017-10-16 15:03 UTC, emileber commented on _includes/next-io.html
> +                <!-- <li><a href="#" class="button style2 big">More Info</a></li> -->
Peut-être un lien vers l'archive des événements?

2017-10-17 01:47 UTC, emileber commented on _data/authors.yml
> +emileber:
Exact

2017-10-17 01:51 UTC, GabLeRoux commented on _data/authors.yml
> +emileber:
We could even use github avatar with a valid `github` key by using this plugin: https://github.com/benbalter/jekyll-avatar 🎉

2017-10-17 01:52 UTC, GabLeRoux approved these changes

2017-10-17 01:54 UTC, emileber commented on _data/authors.yml
> +emileber:
On parle en français partout ailleurs dans ce repo, bien que je préfère l'anglais sur github, c'est assez restreint comme projet.

Ceci dit, je prévois faire une page des auteurs avec photos et plus de détails éventuellement et avec la nouvelle structure, ça va être vraiment facile à ajouter.

2017-10-17 01:54 UTC, GabLeRoux commented on .travis.yml
> +- 2.2.2
This is fixed, we're now using 2.4.2 👍

2017-10-17 01:55 UTC, GabLeRoux commented on _data/authors.yml
> +emileber:
En effet, c'est l'habitude :shipit:

2017-10-17 02:00 UTC, GabLeRoux requested changes
Le logo render mal en smaller resolution. gris sur gris. Le text pour la headline est un peu gris aussi.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/1264761/31643199-38cc1f5a-b2bd-11e7-88ba-98391c9eb6ab.png">

2017-10-17 02:02 UTC, emileber commented
@GabLeRoux ouais j'ai remarqué mais j'ai pas encore trouvé pourquoi. Un affaire avec l'overlay qui chi quand le menu mobile est la... Si tu trouve, je te paye la bière demain, je m'occupe de la FAQ en ce moment et des autres pages.

2017-10-17 02:04 UTC, GabLeRoux commented
Parfait je m'en occupe. 🍻 

J'ai aussi spotté un menu vide en mobile et l'icône hamburger qui render pas:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1264761/31643311-e6854e6e-b2bd-11e7-97fb-262dfa9074c8.png">

2017-10-17 02:08 UTC, emileber commented
@GabLeRoux Ouais le menu est vide parce que j'ai temporairement commenté la main nav, mais il ne sera pas vide aussitôt que j'ajoute les autres pages.

Je vais faire un dernier commit ici, et je propose qu'on fasse plusieurs PR sur la branch `develop` pour continuer le dev sur la nouvelle version et quand on sera satisfait, on fera un merge vers master pour une "release" de l'alpha pour demain.

2017-10-17 02:14 UTC, emileber commented
This closes #77 and #78

2017-10-17 02:31 UTC, merged